# GET https://pokeapi.co/api/v2/pokemon-form/?limit=5&offset=5"

# GET https://pokeapi.co/api/v2/pokemon-form/17/
# GET https://pokeapi.co/api/v2/pokemon-form/?limit=5&offset=5

# GET https://pokeapi.co/api/v2/pokemon-form/76
# GET https://pokeapi.co/api/v2/move/88/
GET  https://pokeapi.co/api/v2/type/6/

//moves
# GET https://pokeapi.co/api/v2/move/88/




